/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-08-16 10:30:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addTags_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      BEANS.SLOGAN SLOGAN = null;
      synchronized (application) {
        SLOGAN = (BEANS.SLOGAN) _jspx_page_context.getAttribute("SLOGAN", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (SLOGAN == null){
          SLOGAN = new BEANS.SLOGAN();
          _jspx_page_context.setAttribute("SLOGAN", SLOGAN, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      BEANS.CSSTotal CSS = null;
      synchronized (application) {
        CSS = (BEANS.CSSTotal) _jspx_page_context.getAttribute("CSS", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (CSS == null){
          CSS = new BEANS.CSSTotal();
          _jspx_page_context.setAttribute("CSS", CSS, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.css1Bean CSS3 = null;
      CSS3 = (BEANS.css1Bean) _jspx_page_context.getAttribute("CSS3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CSS3 == null){
        CSS3 = new BEANS.css1Bean();
        _jspx_page_context.setAttribute("CSS3", CSS3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }

    String slogan = SLOGAN.getSlogan(request);
    String element = request.getParameter("el");
    String s = request.getParameter("s");
    String o = request.getParameter("o");
    String r = request.getParameter("r");
    String src = "";
    String go = "";
    if (o != null) {
        go = "?owner=" + o;
    }
    if (s.equals("files")) {
        src = "fileProp.jsp?id=" + element;
    } else if (s.equals("gallaries") && r == null) {
        src = "gallariesMod.jsp" + go;
    } else if (s.equals("gallaries") && r != null) {
        src = "pic.jsp?id=" + element;
    } else if (s.equals("bloges")) {
        src = "blog.jsp?id=" + element;
    }

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("        <title>Добавить теги</title>\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("        <meta http-equiv=\"content-style-type\" content=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/FILES/alloy/build/aui-skin-classic/css/aui-skin-classic-all-min.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <script src=\"/FILES/alloy/build/aui/aui.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"blue.css\" type=\"text/css\" />\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            @import url('css/topMenu.css');\n");
      out.write("            @import url('css/exxo.css');    \n");
      out.write("            .item-hover {background: red;}\n");
      out.write("            .item-hover  a {color: white;}\n");
      out.write("            #main {position: relative;margin: 10px;width:auto;height: auto;margin-bottom: 10px;background-color: white;padding: 15px;overflow-y: auto;overflow-x: hidden;}\n");
      out.write("            .hov{ color:black; background-color: white; }\n");
      out.write("            .inno{margin:5px;margin-left:20px;}\n");
      out.write("            .cat {background-image: url(\"folder_closed.png\");background-position: left;background-repeat: no-repeat;padding-left: 20px;}\n");
      out.write("            .file-hover {color: red;}\n");
      out.write("            .filepath{color:gray;}\n");
      out.write("            table#small {width: 100%;}\n");
      out.write("            #tdmain {width:40%;}\n");
      out.write("            #tdinfo{width:60%;}\n");
      out.write("            #info{width:auto;height: 100%;padding: 4px;background-color: white; overflow-y: auto;overflow-x: hidden;}\n");
      out.write("            .tagsDiv {padding:3px; display: inline-block; background-color: white; border: 1px solid #bfbfbf;margin:3px;color:black;-moz-border-radius: 4px;\n");
      out.write("                      -webkit-border-radius: 4px;border-radius: 4px; padding-left: 20px; background-image: url('img/tag.png');background-position: 2px center;background-repeat: no-repeat;}\n");
      out.write("            #info {margin:0px;margin-right:10px; margin-left: 10px;}\n");
      out.write("            .tagsDiv:hover {border: 1px solid black;margin:3px;color:white;background-color:gray;cursor:pointer;}\n");
      out.write("            .fil {background-image: url(\"img/tag.png\");background-position: left;background-repeat: no-repeat;padding-left: 20px;}\n");
      out.write("        </style>\n");
      out.write("        <style>");
      out.print(CSS.getCSS(request));
      out.write("</style>\n");
      out.write("        <style>");
      out.print(CSS3.getCSS("addTags.jsp", request));
      out.write("</style>\n");
      out.write("    </head>\n");
      out.write("    <body id=\"addTags_jsp\">\n");
      out.write("        <div id=\"content-wrapper\">\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <table id=\"tableH\">\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td id=\"tdlogo\">\n");
      out.write("                                <img src=\"logo.png\" id=\"logo\"></td>\n");
      out.write("                            <td>\n");
      out.write("                                <div id=\"head\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td id=\"slogan\" valign=\"center\">");
      out.print( slogan);
      out.write("</td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "poisk", out, true);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"foot\">\n");
      out.write("                                    <ul class=\"topMenu\">\n");
      out.write("                                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.xhtml", out, true);
      out.write("\n");
      out.write("                                        <li><a href=\"");
      out.print( src);
      out.write("\" class=\"footmenu\">Sonlandır</a></li>\n");
      out.write("                                        <li> <a href=\"http://exxo.ru/howto/knowledge-management-howto.html#tags\" class=\"footmenu howto\" target=\"_blank\">?</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <table id=\"grid\" class=\"grid\">\n");
      out.write("                <tbody id=\"atbody\">\n");
      out.write("                    <tr id=\"tr\">\n");
      out.write("                        <td id=\"column-3\" valign=\"top\"> \n");
      out.write("                            <table id=\"small\">\n");
      out.write("                                <tbody>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td id=\"tdmain\"  valign=\"top\">\n");
      out.write("                                            <div id=\"main\" class=\"exxo-shadow\"></div>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td id=\"tdinfo\"  valign=\"top\">\n");
      out.write("                                            <div id=\"info\" class=\"exxo-shadow\"></div> \n");
      out.write("                                        </td> \n");
      out.write("                                    </tr>\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </td>\n");
      out.write("                    </tr> \n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("                \n");
      out.write("        </div>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            AUI().ready('aui-io', function (A) {\n");
      out.write("                var myHeight = A.DOM.winHeight() - 175;\n");
      out.write("                if (myHeight < 300)\n");
      out.write("                    myHeight = 300;\n");
      out.write("                Reload(\"1\", null);\n");
      out.write("                function Reload(superior, id) {\n");
      out.write("                    A.one(\"#main\").unplug(A.Plugin.IO);\n");
      out.write("                    var data = {superior: superior};\n");
      out.write("                    if (id != null)\n");
      out.write("                        data = {id: id};\n");
      out.write("                    var DATA = {s: '");
      out.print( s);
      out.write("', element: '");
      out.print(element);
      out.write("'};\n");
      out.write("                    reInfo(DATA);\n");
      out.write("                    A.one(\"#main\").plug(A.Plugin.IO, {uri: 'tagClassic', method: 'POST',\n");
      out.write("                        data: data,\n");
      out.write("                        on: {'end': function (event) {\n");
      out.write("                                A.all(\".cat\").each(function () {\n");
      out.write("                                    this.on(\"mouseover\", function () {\n");
      out.write("                                        this.addClass(\"file-hover\");\n");
      out.write("                                    })\n");
      out.write("                                });\n");
      out.write("                                A.all(\".fil\").each(function () {\n");
      out.write("                                    this.on(\"click\", function () {\n");
      out.write("                                        this.addClass(\"file-hover\");\n");
      out.write("                                        var fileID = this.get(\"id\");\n");
      out.write("                                        var DATA = {id: fileID, s: '");
      out.print( s);
      out.write("', element: '");
      out.print(element);
      out.write("'};\n");
      out.write("                                        reInfo(DATA);\n");
      out.write("                                    })\n");
      out.write("                                });\n");
      out.write("                                A.all(\".item\").each(function () {\n");
      out.write("                                    this.on(\"mouseout\", function () {\n");
      out.write("                                        this.removeClass(\"file-hover\");\n");
      out.write("                                    })\n");
      out.write("                                });\n");
      out.write("                                A.all(\".cat\").each(function () {\n");
      out.write("                                    this.on(\"click\", function () {\n");
      out.write("                                        if (!this.hasClass(\"upper\"))\n");
      out.write("                                            Reload(this.get(\"id\"), null);\n");
      out.write("                                        else\n");
      out.write("                                            Reload(null, this.get(\"id\"));\n");
      out.write("                                    })\n");
      out.write("                                });\n");
      out.write("                            }}})\n");
      out.write("                }\n");
      out.write("                A.one(\"#main\").setStyle(\"height\", myHeight + \"px\");\n");
      out.write("                A.one(\"#info\").setStyle(\"height\", myHeight + \"px\");\n");
      out.write("                function reInfo(data) {\n");
      out.write("                    A.one(\"#info\").unplug(A.Plugin.IO);\n");
      out.write("                    A.one(\"#info\").plug(A.Plugin.IO, {uri: 'tagInfo', data: data, method: 'POST',\n");
      out.write("                        on: {'end': function () {\n");
      out.write("                                A.all(\".tagsDiv\").each(function () {\n");
      out.write("                                    this.on(\"click\", function () {\n");
      out.write("                                        if (window.confirm('Удалить тег?')) {\n");
      out.write("                                            var id = this.getAttribute('id');\n");
      out.write("                                            A.io.request(\"dropTag\", {method: 'post', data: {id: id, s: '");
      out.print( s);
      out.write("', element: '");
      out.print(element);
      out.write("'}}\n");
      out.write("                                            );\n");
      out.write("                                            this.remove();\n");
      out.write("                                        }\n");
      out.write("                                    })\n");
      out.write("                                });\n");
      out.write("                            }}});\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/poisk.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/topMenu.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
