/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-08-21 08:00:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      BEANS.SLOGAN SLOGAN = null;
      synchronized (application) {
        SLOGAN = (BEANS.SLOGAN) _jspx_page_context.getAttribute("SLOGAN", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (SLOGAN == null){
          SLOGAN = new BEANS.SLOGAN();
          _jspx_page_context.setAttribute("SLOGAN", SLOGAN, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      BEANS.CSSTotal CSS = null;
      synchronized (application) {
        CSS = (BEANS.CSSTotal) _jspx_page_context.getAttribute("CSS", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (CSS == null){
          CSS = new BEANS.CSSTotal();
          _jspx_page_context.setAttribute("CSS", CSS, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.css1Bean CSS3 = null;
      CSS3 = (BEANS.css1Bean) _jspx_page_context.getAttribute("CSS3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CSS3 == null){
        CSS3 = new BEANS.css1Bean();
        _jspx_page_context.setAttribute("CSS3", CSS3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      BEANS.BlogBean BLOG = null;
      BLOG = (BEANS.BlogBean) _jspx_page_context.getAttribute("BLOG", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (BLOG == null){
        BLOG = new BEANS.BlogBean();
        _jspx_page_context.setAttribute("BLOG", BLOG, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }

    String owner = (String) session.getAttribute("id");
    String role = (String) session.getAttribute("role");
    String id = request.getParameter("id");
    String comJS = "";
    String ansJS = "";
    if (request.getParameter("comments") != null) {
        comJS = "A.one('#listTable').scrollIntoView ( );";
    }
    if (request.getParameter("answers") != null) {
        comJS = "A.one('#listTable').scrollIntoView ( );";
    }
    String answers = "";
    boolean a = false;
    boolean r = false;
    boolean c = false;
    if (request.getParameter("answers") != null) {
        a = true;
    }
    if (request.getParameter("respect") != null) {
        r = true;
    }
    if (request.getParameter("comments") != null) {
        c = true;
    }
    if (id == null || id.equals("")) {
        response.sendRedirect("notPermited.html");
    }
    BLOG.setOwner(owner, id, role, (String) session.getAttribute("global_id"), a, r, c);
    String emp = BLOG.getEmp(request);
    String list = BLOG.getList();
    String slogan = SLOGAN.getSlogan(request);
    Boolean diff = BLOG.getDiff();
    String ansCount = BLOG.getAns();
    String count = BLOG.getCount();
    String commCount = BLOG.getCommCount();
    String respcount = BLOG.getRespcount();
    answers = BLOG.getAnswers();
    String comments = BLOG.getComments();
    if (BLOG.getNotPermitted()) {
        response.sendRedirect("notPermited.html");
    }

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("        <title>Mesajlar</title>\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta http-equiv=\"content-style-type\" content=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/FILES/alloy/build/aui-skin-classic/css/aui-skin-classic-all-min.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <script src=\"/FILES/alloy/build/aui/aui.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\" /><link rel=\"stylesheet\" href=\"blue.css\" type=\"text/css\" />\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            @import url('css/topMenu.css');\n");
      out.write("            @import url('css/exxo.css');\n");
      out.write("            #content {width:90%;height:auto;position: relative; margin:0px 10px;overflow-x: hidden;overflow-y: auto; background-color: white ;border-color: #DEDEDE #DEDEDE #BFBFBF #DEDEDE;border-width: 1px;border-style: solid;}\n");
      out.write("            span.hoverPlus {color:red;}\n");
      out.write("            #commentator {margin: 15px;padding:20px;position: absolute;z-index: 99998;top:0px;;height: auto;width: 700px;color: black;\n");
      out.write("                          background-color: white;display: none;overflow: auto;}\n");
      out.write("            .close, #closer,#closser {color:red;width:100%;text-align:right;}\n");
      out.write("            .text {font-size:10pt;padding-bottom: 10px;text-align: justify;}\n");
      out.write("            .timer {font-size: 11px;color: #3B3B8F;text-align: right;}\n");
      out.write("            .HBlog{text-align: right;}\n");
      out.write("            .bus {color:#0F1F99;}\n");
      out.write("            .blog {margin-bottom: 20px;background-color: white;padding: 10px;padding-top: 5px;padding-bottom: 5px;clear: both;}\n");
      out.write("            .B {padding-left: 10px;}\n");
      out.write("            #plus, #plusik {font-size: 14pt;text-align: right;margin-bottom: 20px;}\n");
      out.write("            #plus span, #plusik span {padding-left: 20px;}\n");
      out.write("            .BUS {border-color: #0F1F99;border-style: solid;border-width: 1px;}\n");
      out.write("            #containerImg img.photo {margin: 2px;}\n");
      out.write("            .hov{color:black;background-color: white;}\n");
      out.write("            .inno{margin:5px;margin-left:20px;}\n");
      out.write("            #closer {width:90%;}\n");
      out.write("            #imger {position: absolute;display: none;left:20px;top:20px;padding: 10px;background-color: black;z-index: 9999999;}\n");
      out.write("            .text {padding: 20px;padding-top:20px;padding-left: 30px;}\n");
      out.write("            #blogs {width: 700px; margin: auto auto; overflow: hidden;}\n");
      out.write("            #blogs .blog {border:0}\n");
      out.write("            #back {padding-right:40px; text-align: right;}\n");
      out.write("            .empInfo {width:100%; margin-left: 0px; }\n");
      out.write("            .empInfo .left {width:100px; padding:20px 0px;}\n");
      out.write("            .empInfo .right {font-size:14px; vertical-align: top; padding-top: 20px; text-align:left;}\n");
      out.write("            #bottomBlog {text-align: right;background-color: rgb(248, 248, 248); padding: 10px 5px;border-top: 1px solid #dedede;}\n");
      out.write("            #bottomBlog a {padding-right: 30px; text-decoration: none;}\n");
      out.write("            #bottomBlog:hover a, .results:hover a {color: #972626;}\n");
      out.write("            #bottomBlog a:hover, .results a:hover {text-decoration: underline;}\n");
      out.write("            .results a {text-decoration: none;}\n");
      out.write("            #listTable td {padding: 5px; padding-top: 10px; padding-bottom: 10px;}\n");
      out.write("            #listTable  a {font-size:12px; text-decoration: none; color:black;}\n");
      out.write("            #listTable tr:hover  a {color: #972626;}\n");
      out.write("            #listTable  a.bus {color:#0F1F99;}\n");
      out.write("            #listTable tr:hover  a.bus {color: #972626;}\n");
      out.write("            #listTable {margin: 0px 0px; width: 100%;}\n");
      out.write("            #listTable  a:hover {text-decoration: underline;}\n");
      out.write("            .results {background-color: rgb(248, 248, 248); padding: 10px 5px;}\n");
      out.write("            .results:last-of-type {border-bottom: 1px solid #dedede;}\n");
      out.write("            .results a, .results span {padding-left: 20px;}\n");
      out.write("            #listTable td.type_0, #listTable td.type_1,#listTable td.type_2,#listTable td.type_3,#listTable td.type_4 {padding: 0;}\n");
      out.write("            .fio {color:black; font-size:12px; padding-right: 10px; text-align: left;}\n");
      out.write("            .RE {margin-bottom:5px;}\n");
      out.write("            #submitComment {padding: 10px; cursor: pointer;}\n");
      out.write("            #closeCom {cursor: pointer; margin-bottom: 10px;}\n");
      out.write("            input#submit, #commentator input[type=submit] {margin: 20px auto; display: block; width: 110px; padding: 5px;}\n");
      out.write("            #commentator {width: 650px;}\n");
      out.write("            #commentator textarea {width: 630px; height: 200px;border: 1px solid #DEDEDE;overflow: auto;}\n");
      out.write("            #img img {width: 50px; height: 67px; margin-left: 10px;}\n");
      out.write("            #blogs #name {color: gray; text-align: center; font-size: 18px;}\n");
      out.write("            #blogs:hover .B {color:#972626;}\n");
      out.write("            a.B {text-decoration: none;}\n");
      out.write("            div.RE a, div.DOCRe a{text-decoration: none;}\n");
      out.write("            #blogs:hover div.RE a,  #blogs:hover div.DOCRe a{color:#972626;}\n");
      out.write("            #blogs div.RE a:hover, #blogs div.DOCRe a:hover {text-decoration: underline;}\n");
      out.write("            .B:hover {text-decoration: underline;}\n");
      out.write("            .time {color:#3B3B8F; font-size:11px;}\n");
      out.write("            table#nav {width: 100%; border-bottom: 1px solid #dedede;margin-bottom: 20px; background-color:rgb(248, 248, 248)}\n");
      out.write("            table#nav td.navThree{padding: 5px; width: 35%; padding-right: 20px; text-align: left;}\n");
      out.write("            table#nav td.navTwo{background-image:url('small/forward-big.png'); background-position: center center; background-repeat: no-repeat; width: 30%;}\n");
      out.write("            table#nav td.navThree a, table#nav td.navOne a {text-decoration: none;}\n");
      out.write("            table#nav td.navThree:hover a, table#nav td.navOne:hover a {color: #972626;}\n");
      out.write("            table#nav td.navThree a:hover,  table#nav td.navOne a:hover{text-decoration: underline;}\n");
      out.write("            ");
if (!diff) {
      out.write("table#nav td.navTwo:hover {background-image:url('small/forward-big1.png'); cursor: pointer;}");
}
      out.write("\n");
      out.write("            #listShrim {width: 100%;}\n");
      out.write("            td.empIMG img {width: 50px; height: 67px;}\n");
      out.write("            #listTable td.empIMG {width: 60px; padding: 5px; padding-left: 10px; padding-right: 0px;padding-top: 10px; padding-bottom: 10px;}\n");
      out.write("            #tags {margin-top: 10px;}\n");
      out.write("            .fio {color:black; font-size:12px; padding-right: 10px;  padding-left: 10px; text-align: left;}\n");
      out.write("            .fio>span {padding-left: 10px;}\n");
      out.write("            .fio a{font-size: 10px; font-weight: bold;}\n");
      out.write("            .tdName::before {content: ' ';height: 0;position: absolute;width: 0;border: 8px solid transparent;border-right-color: #dedede;right: 100%;top: 10px;}\n");
      out.write("            .tdName::after {content: ' ';height: 0;position: absolute;width: 0;border: 6px solid transparent;border-right-color: #FDF2F2;right: 100%;top: 12px;}\n");
      out.write("            #listTable td.tdComment {vertical-align: top; position: relative;}\n");
      out.write("            .tdName {position: relative; padding: 10px; border: 1px solid #dedede; border-radius: 5px; background-color: #FDF2F2;}\n");
      out.write("            .empIMG img {border-radius: 5px;}\n");
      out.write("            #listTable .fio a {font-size: 10px;}\n");
      out.write("            table.exxo-table tr:nth-of-type(odd) td {background-color: white;}\n");
      out.write("            table.exxo-table tr:hover td {background-color: #E3E2FD; cursor: pointer;}\n");
      out.write("            table.exxo-table {margin-bottom:20px; margin-top: 10px;}\n");
      out.write("            table.exxo-table tr:first-of-type td {border-top: 1px solid #dedede;}\n");
      out.write("            #input {color: gray; margin-left: 20px;}\n");
      out.write("            div.text img {max-width: 100%;}\n");
      out.write("        </style>\n");
      out.write("        <style>");
      out.print(CSS.getCSS(request));
      out.write("</style>\n");
      out.write("        <style>");
      out.print(CSS3.getCSS("blog.jsp", request));
      out.write("</style>\n");
      out.write("    </head>\n");
      out.write("    <body id=\"blog_jsp\">\n");
      out.write("        <div id=\"content-wrapper\">\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <table id=\"tableH\">\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td id=\"tdlogo\">\n");
      out.write("                                <img src=\"logo.png\" id=\"logo\">\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <div id=\"head\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td id=\"slogan\" valign=\"center\">\n");
      out.write("                                                    ");
      out.print( slogan);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "poisk", out, true);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"foot\">\n");
      out.write("                                    <ul class=\"topMenu\">\n");
      out.write("                                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.xhtml", out, true);
      out.write("\n");
      out.write("                                        <li> \n");
      out.write("                                            <a href=\"http://exxo.ru/howto/mail-howto.html#comunication\" class=\"footmenu howto\" target=\"_blank\">?</a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <table id=\"grid\" class=\"grid\">\n");
      out.write("                <tbody id=\"atbody\">\n");
      out.write("                    <tr id=\"tr\">\n");
      out.write("                        <td id=\"menu-td\" class=\"menu-td\" valign=\"top\">\n");
      out.write("                            <div class=\"exxo-menu exxo-shadow\" id=\"menu\">\n");
      out.write("                                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-blog.xhtml", out, true);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                        <td id=\"column-3\" valign=\"top\">\n");
      out.write("                            <div id=\"content\" class=\"exxo-shadow\">\n");
      out.write("                                <table id=\"nav\">\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td class=\"navOne\">");
      out.print(emp);
      out.write("</td>\n");
      out.write("                                        <td class=\"navTwo\"></td>\n");
      out.write("                                        <td class=\"navThree\">\n");
      out.write("                                            ");
      out.print( BLOG.too);
      out.print( BLOG.tags);
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </table>\n");
      out.write("                                <table id=\"listShrim\">\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>\n");
      out.write("                                            ");
      out.print(list);
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                </table>\n");
      out.write("                                <div id=\"bottomBlog\">\n");
      out.write("                                    <a href=\"javascript:;\" id=\"addComment\">ŞƏRHLƏR</a>\n");
      out.write("                                    <a href=\"blogInsert.jsp?id=");
      out.print( id);
      out.write("&r=1\">CAVAB</a>\n");
      out.write("                                    <a href=\"blog.jsp?id=");
      out.print( id);
      out.write("&amp;respect=1\">RAZILAŞMA</a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"results\"> \n");
      out.write("                                    <span>Просмотров:</span> \n");
      out.write("                                    ");
      out.print(count);
      out.write("\n");
      out.write("                                    <span>Согласились:</span> \n");
      out.write("                                    ");
      out.print(respcount);
      out.write("\n");
      out.write("                                    <a href=\"blog.jsp?id=");
      out.print( id);
      out.write("&amp;answers=1\">cavablar:</a> \n");
      out.write("                                    ");
      out.print( ansCount);
      out.write("\n");
      out.write("                                    <a href=\"blog.jsp?id=");
      out.print( id);
      out.write("&amp;comments=1\">şərhlər:</a> \n");
      out.write("                                    ");
      out.print( commCount);
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"results\"> \n");
      out.write("                                    ");
 if (a) {
      out.write("\n");
      out.write("                                    <a href=\"blog.jsp?id=");
      out.print( id);
      out.write("\">cavablamanı bitir</a>\n");
      out.write("                                    ");
}
 if (c) {
      out.write("\n");
      out.write("                                    <a href=\"blog.jsp?id=");
      out.print( id);
      out.write("\">şərhi bitir</a>\n");
      out.write("                                    ");
}
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                ");
      out.print( answers);
      out.print( comments);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr> \n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FOOTER", out, true);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div id=\"commentator\"> \n");
      out.write("            <div class=\"close\" id=\"closeCom\">\n");
      out.write("                <span>BAĞLA</span>\n");
      out.write("            </div>\n");
      out.write("            <form action=\"comment\" method=\"post\" id=\"forma\">\n");
      out.write("                <textarea name=\"comment\" id=\"comment\" cols=\"70\" rows=\"10\"></textarea>\n");
      out.write("                <input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("                <input type=\"submit\" id='submitComment' value=\"Yadda Saxla\"></form></div>\n");
      out.write("        <div id=\"imger\">\n");
      out.write("            <div id=\"closser\">\n");
      out.write("                <span>BAĞLA</span>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"imgerViewer\"></div>\n");
      out.write("                \n");
      out.write("        </div>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            AUI().ready('anim', 'aui-overlay-mask', 'aui-button-item', 'aui-io', function (A) {\n");
      out.write("                var overlayMask = new A.OverlayMask().render();\n");
      out.write("                var myEditor;\n");
      out.write("                var myHeight = A.DOM.winHeight() - 150;\n");
      out.write("                if (myHeight < 300)\n");
      out.write("                    myHeight = 300;\n");
      out.write("                var HH = myHeight - 80;\n");
      out.write("                if (HH < 250)\n");
      out.write("                    HH = 250;\n");
      out.write("            ");
if (!diff) {
      out.write("\n");
      out.write("                A.one(\"td.navTwo\").on(\"click\", function () {\n");
      out.write("                    location = \"addTags.jsp?el=");
      out.print(id);
      out.write("&s=bloges\"\n");
      out.write("                });\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("                function closser(node) {\n");
      out.write("                    node.fx.run();\n");
      out.write("                }\n");
      out.write("                A.all(\"a.imger\").each(function () {\n");
      out.write("                    var href = this.getAttribute('href');\n");
      out.write("                    this.setAttribute('href', 'javascript:')\n");
      out.write("                    this.on(\"click\", function () {\n");
      out.write("                        A.one('#imger').fx.run();\n");
      out.write("                        var html = \"<img src='\" + href + \"'>\";\n");
      out.write("                        A.one(\"#imgerViewer\").html(html).scrollIntoView( );\n");
      out.write("                    });\n");
      out.write("                })\n");
      out.write("                A.one('#closser span').on('click', function (event) {\n");
      out.write("                    closser(A.one(\"#imger\"));\n");
      out.write("                });\n");
      out.write("            ");
if (!diff) { 
      out.write("\n");
      out.write("                A.one(\".aui-overlaymask-content\").setStyle(\"height\", \"100%\");\n");
      out.write("            ");
 }
      out.write("\n");
      out.write("                A.one(\"#addComment\").on(\"click\", function () {\n");
      out.write("                    A.one('#commentator').fx.run();\n");
      out.write("                    A.one('#commentator').scrollIntoView( );\n");
      out.write("                });\n");
      out.write("                A.one(\"#closeCom\").on(\"click\", function () {\n");
      out.write("                    closser(A.one(\"#commentator\"));\n");
      out.write("                });\n");
      out.write("                A.one(\"#grid\").setStyle(\"minHeight\", myHeight + \"px\");\n");
      out.write("                A.one(\".aui-overlaymask-content\").setStyle(\"height\", \"100%\");\n");
      out.write("            ");
      out.print(comJS);
      out.print(ansJS);
      out.write("\n");
      out.write("                A.all(\"#listShrim table.exxo-table tr\").each(function () {\n");
      out.write("                    this.on('click', function () {\n");
      out.write("                        location = \"fileLoader.jsp?id=\" + this.getAttribute(\"id\");\n");
      out.write("                    })\n");
      out.write("                });\n");
      out.write("                var overlayMask = new A.OverlayMask().render();\n");
      out.write("                A.one('#imger').setStyle('opacity', '0');\n");
      out.write("                A.one('#commentator').setStyle('opacity', '0');\n");
      out.write("                var div = A.one('#imger');\n");
      out.write("                var conf = {\n");
      out.write("                    from: {opacity: 0},\n");
      out.write("                    to: {opacity: 1},\n");
      out.write("                    on: {'start': function () {\n");
      out.write("                            if (!this.get('reverse')) {\n");
      out.write("                                overlayMask.set('target', document).show();\n");
      out.write("                                this.get('node').setStyle('display', 'block');\n");
      out.write("                            }\n");
      out.write("                        }},\n");
      out.write("                    after: {'end': function () {\n");
      out.write("                            this.set('reverse', !this.get('reverse'));\n");
      out.write("                            this.stop();\n");
      out.write("                            if (this.get('node').getStyle('opacity') == 0)\n");
      out.write("                                this.get('node').setStyle('display', 'none');\n");
      out.write("                            if (!this.get('reverse'))\n");
      out.write("                                overlayMask.set('target', document).hide();\n");
      out.write("                        }}};\n");
      out.write("                div.setStyle('opacity', '0');\n");
      out.write("                div.plug(A.Plugin.NodeFX, conf);\n");
      out.write("                A.one('#commentator').plug(A.Plugin.NodeFX, conf);\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/poisk.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/topMenu.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
