/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-08-16 11:05:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blogEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      BEANS.SLOGAN SLOGAN = null;
      synchronized (application) {
        SLOGAN = (BEANS.SLOGAN) _jspx_page_context.getAttribute("SLOGAN", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (SLOGAN == null){
          SLOGAN = new BEANS.SLOGAN();
          _jspx_page_context.setAttribute("SLOGAN", SLOGAN, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      BEANS.CSSTotal CSS = null;
      synchronized (application) {
        CSS = (BEANS.CSSTotal) _jspx_page_context.getAttribute("CSS", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (CSS == null){
          CSS = new BEANS.CSSTotal();
          _jspx_page_context.setAttribute("CSS", CSS, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.css1Bean CSS3 = null;
      CSS3 = (BEANS.css1Bean) _jspx_page_context.getAttribute("CSS3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CSS3 == null){
        CSS3 = new BEANS.css1Bean();
        _jspx_page_context.setAttribute("CSS3", CSS3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      BEANS.BlogEditorBean BLOG = null;
      BLOG = (BEANS.BlogEditorBean) _jspx_page_context.getAttribute("BLOG", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (BLOG == null){
        BLOG = new BEANS.BlogEditorBean();
        _jspx_page_context.setAttribute("BLOG", BLOG, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }

    String owner = (String) session.getAttribute("id");
    String list = BLOG.getList(owner, request);
    String slogan = SLOGAN.getSlogan(request);

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("        <title>Bloqdaki qaramalar</title>\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta http-equiv=\"content-style-type\" content=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/FILES/alloy/build/aui-skin-classic/css/aui-skin-classic-all-min.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <script src=\"/FILES/alloy/build/aui/aui.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"blue.css\" type=\"text/css\" />\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            @import url('css/topMenu.css');\n");
      out.write("            @import url('css/exxo.css');\n");
      out.write("            #content {width:90%;height:auto;position: relative;padding:5px;margin:0px 10px;overflow-x: hidden;overflow-y: auto; background-color:white;\n");
      out.write("                      border-color: #DEDEDE #DEDEDE #BFBFBF #DEDEDE;border-width: 1px;border-style: solid;}\n");
      out.write("            span.hoverPlus {color:red;}\n");
      out.write("            .close, #closer,#closser {color:red;width:100%;text-align:right;}\n");
      out.write("            .text {font-size:10pt;padding-bottom: 10px;text-align: justify;}\n");
      out.write("            .text {padding: 20px;padding-top:20px;padding-left: 30px;}\n");
      out.write("            .HBlog{text-align: center;margin-bottom: 20px;}\n");
      out.write("            .bus {color:green;}\n");
      out.write("            .blog {margin-bottom: 20px;background-color: white;padding: 10px;padding-top: 5px;padding-bottom: 5px;clear: both;}\n");
      out.write("            .B {padding-left: 10px; text-decoration: none;}\n");
      out.write("            #plus, #plusik {font-size: 14pt;text-align: right;margin-bottom: 20px;}\n");
      out.write("            #plus span, #plusik span {padding-left: 20px;}\n");
      out.write("            .BUS {border-color: green;border-style: solid;border-width: 1px;}\n");
      out.write("            #imges {position:absolute;z-index:99999;width:100%;height:100%;top:0px;left:0px;background-color:white;display:none;}\n");
      out.write("            #inserter {width:90%;height: 80%;margin: 5px;margin-top: 10px;border-color: gray;border-width: 1px;border-style: solid;overflow-y: auto;\n");
      out.write("                       overflow-x: hidden;}\n");
      out.write("            #containerImg img.photo {margin: 2px;}\n");
      out.write("            .hov{color:black;background-color: white;}\n");
      out.write("            #closer {width:90%;}\n");
      out.write("            #imger {position: absolute;display: none;left:20px;top:20px;padding: 10px;background-color: black;z-index: 9999999;}\n");
      out.write("            #blogs {width: 700px; margin: auto auto; overflow: hidden;}\n");
      out.write("            #blogs .blog {border:0}\n");
      out.write("            #addBlog {font-size: 16px; text-align: center;}\n");
      out.write("            #blogs #name {color: gray; text-align: center; font-size: 18px;}\n");
      out.write("            #blogs:hover .B {color:#972626;}\n");
      out.write("            .B:hover {text-decoration: underline;}\n");
      out.write("            #addBlog {padding:50px;}\n");
      out.write("            #addBlog a{text-decoration: none}\n");
      out.write("            #addBlog:hover a{color:#972626;}\n");
      out.write("            #addBlog a:hover {text-decoration: underline;}\n");
      out.write("            table.exxo-table tr:nth-of-type(odd) td {background-color: white;}\n");
      out.write("            table.exxo-table tr:hover td {background-color: #E3E2FD; cursor: pointer;}\n");
      out.write("            table.exxo-table {margin:100px; margin-top: 10px;}\n");
      out.write("            table.exxo-table tr:first-of-type td {border-top: 1px solid #bfbfbf;}\n");
      out.write("            #input {color: gray; margin-left: 100px;}\n");
      out.write("            div.text img {max-width: 100%;}\n");
      out.write("        </style>\n");
      out.write("        <style>\n");
      out.write("            ");
      out.print(CSS.getCSS(request));
      out.write("\n");
      out.write("        </style>\n");
      out.write("        <style>\n");
      out.write("            ");
      out.print(CSS3.getCSS("blogEditor.jsp", request));
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body id=\"blogEditor_jsp\">\n");
      out.write("        <div id=\"content-wrapper\">\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <table id=\"tableH\">\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td id=\"tdlogo\">\n");
      out.write("                                <img src=\"logo.png\" id=\"logo\">\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <div id=\"head\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td id=\"slogan\" valign=\"center\">");
      out.print( slogan);
      out.write("</td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "poisk", out, true);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"foot\">\n");
      out.write("                                    <ul class=\"topMenu\">\n");
      out.write("                                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.xhtml", out, true);
      out.write("\n");
      out.write("                                        <li> \n");
      out.write("                                            <a href=\"http://exxo.ru/howto/mail-howto.html#send\" class=\"footmenu howto\" target=\"_blank\">?</a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <table id=\"grid\" class=\"grid\">\n");
      out.write("                <tbody id=\"atbody\">\n");
      out.write("                    <tr id=\"tr\">\n");
      out.write("                        <td id=\"menu-td\" class=\"menu-td\" valign=\"top\">\n");
      out.write("                            <div class=\"exxo-menu exxo-shadow\" id=\"menu\">\n");
      out.write("                                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-blog.xhtml", out, true);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                        <td id=\"column-3\" valign=\"top\">\n");
      out.write("                            <div id=\"content\" class=\"exxo-shadow\">\n");
      out.write("                                ");
      out.print(list);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr> \n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FOOTER", out, true);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div id=\"imger\"><div id=\"closser\"><span>BAĞLA</span></div><div id=\"imgerViewer\"></div></div>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            AUI().ready('anim', 'aui-overlay-mask', function (A) {\n");
      out.write("                var overlayMask = new A.OverlayMask().render();\n");
      out.write("                var myEditor;\n");
      out.write("                var myHeight = A.DOM.winHeight() - 150;\n");
      out.write("                if (myHeight < 300)\n");
      out.write("                    myHeight = 300;\n");
      out.write("                var HH = myHeight - 80;\n");
      out.write("                if (HH < 250)\n");
      out.write("                    HH = 250;\n");
      out.write("                A.all(\"a.imger\").each(function () {\n");
      out.write("                    var href = this.getAttribute('href');\n");
      out.write("                    this.setAttribute('href', 'javascript:');\n");
      out.write("                    this.on(\"click\", function () {\n");
      out.write("                        overlayMask.set('target', document).show();\n");
      out.write("                        A.one('#imger').setStyle('display', 'block');\n");
      out.write("                        anim.run();\n");
      out.write("                        var html = \"<img src='\" + href + \"'>\";\n");
      out.write("                        A.one(\"#imgerViewer\").html(html).scrollIntoView( );\n");
      out.write("                    });\n");
      out.write("                });\n");
      out.write("                var overlayMask = new A.OverlayMask().render();\n");
      out.write("                A.one('#imger').setStyle('opacity', '0');\n");
      out.write("                A.one('#imger').setStyle('display', 'none');\n");
      out.write("                var anim = new A.Anim({node: '#imger', to: {opacity: 1}, on: {'start': function () {\n");
      out.write("                            A.one(\"#imger\").setStyle('display', 'block');\n");
      out.write("                            A.one('#closser span').scrollIntoView( )\n");
      out.write("                        }}});\n");
      out.write("                var anim1 = new A.Anim({node: '#imger', to: {opacity: 0}, on: {'end': function () {\n");
      out.write("                            A.one(\"#imger\").setStyle('display', 'none');\n");
      out.write("                            overlayMask.hide();\n");
      out.write("                        }}});\n");
      out.write("                A.one('#closser span').on('click', function (event) {\n");
      out.write("                    closer(A.one(\"#imger\"));\n");
      out.write("                });\n");
      out.write("                function closer(node) {\n");
      out.write("                    anim1.run();\n");
      out.write("                }\n");
      out.write("                //A.one(\"#content\").setStyle(\"height\",myHeight+\"px\");\n");
      out.write("                A.all(\"#content table.exxo-table tr\").each(function () {\n");
      out.write("                    this.on('click', function () {\n");
      out.write("                        location = \"fileLoader.jsp?id=\" + this.getAttribute(\"id\");\n");
      out.write("                    })\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/poisk.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/topMenu.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
