/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-08-16 11:09:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class empDoc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      BEANS.SLOGAN SLOGAN = null;
      synchronized (application) {
        SLOGAN = (BEANS.SLOGAN) _jspx_page_context.getAttribute("SLOGAN", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (SLOGAN == null){
          SLOGAN = new BEANS.SLOGAN();
          _jspx_page_context.setAttribute("SLOGAN", SLOGAN, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      BEANS.CSSTotal CSS = null;
      synchronized (application) {
        CSS = (BEANS.CSSTotal) _jspx_page_context.getAttribute("CSS", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (CSS == null){
          CSS = new BEANS.CSSTotal();
          _jspx_page_context.setAttribute("CSS", CSS, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.css1Bean CSS3 = null;
      CSS3 = (BEANS.css1Bean) _jspx_page_context.getAttribute("CSS3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CSS3 == null){
        CSS3 = new BEANS.css1Bean();
        _jspx_page_context.setAttribute("CSS3", CSS3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      BEANS.EmpDoc ND = null;
      ND = (BEANS.EmpDoc) _jspx_page_context.getAttribute("ND", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ND == null){
        ND = new BEANS.EmpDoc();
        _jspx_page_context.setAttribute("ND", ND, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }

    String o = (String) session.getAttribute("id");
    String g = (String) session.getAttribute("global_id");
    String l = "";
    String ll = "";
    boolean itsMe = false;
    if (request.getParameter("own") != null && !request.getParameter("own").equals(o)) {
        l = "&own=" + request.getParameter("own");
        ll = "?owner=" + request.getParameter("own");
    } else if (request.getParameter("own") == null || request.getParameter("own").equals(o)) {
        itsMe = true;
    }
    String list = ND.getList(request, o, g);
    String slogan = SLOGAN.getSlogan(request);

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("        <title>Yeni sənədlər</title>\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta http-equiv=\"content-style-type\" content=\"text/css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"/FILES/alloy/build/aui-skin-classic/css/aui-skin-classic-all-min.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <script src=\"/FILES/alloy/build/aui/aui.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"blue.css\" type=\"text/css\" />\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            @import url('css/topMenu.css');\n");
      out.write("            @import url('css/exxo.css');\n");
      out.write("            #content {width:95%;position: relative;margin:0px 10px;}\n");
      out.write("            #content table tr {border-top: 1px solid #DEDEDE;}\n");
      out.write("            #content table {width: 100%;background-color: white; border-left: 1px solid #DEDEDE;\n");
      out.write("                            border-right: 1px solid #DEDEDE; border-bottom: 1px solid #BFBFBF;}\n");
      out.write("            #content table tr:nth-of-type(odd) td{background-color: #F5F2F2;}\n");
      out.write("            .fil {padding-left: 20px;\n");
      out.write("                  font-size: 11px;width: 30%;}\n");
      out.write("            .fil a{font-size: 12px;margin-right: 10px;text-decoration: none;}\n");
      out.write("            .fio a{font-size: 11px;text-decoration: none;}\n");
      out.write("            .descr {padding-left:  20px; font-size:11px;}\n");
      out.write("            #content table tr:hover td{background-color: #E3E2FD;}\n");
      out.write("            #content td {padding: 4px 10px; text-align: left;}\n");
      out.write("            #column-3 #content {border: 0;}\n");
      out.write("            .created {font-size: 10px; width: 70px; color: #3B3B8F;}\n");
      out.write("            .aui-icon-dgeneral {background-image: url('small/lock_unlock.png');}\n");
      out.write("            .aui-icon-dproject {background-image: url('small/flag_blue.png');}\n");
      out.write("            .aui-icon-dgroup {background-image: url('small/group.png');}\n");
      out.write("            .aui-icon-dunit {background-image: url('small/user_business_boss.png');}\n");
      out.write("            .aui-icon-dprivat {background-image: url('small/envelope.png');}\n");
      out.write("            #buttonsDons {margin-left: 10px;}\n");
      out.write("            #buttonsDons button {height: 24px; padding-top: 5px; min-width: 26px; margin-top: 10px;}\n");
      out.write("            #buttonsDons .aui-button-label {font-size: 12px;}\n");
      out.write("            ");
 if (!itsMe) { 
      out.write("a.nopend {font-weight: bold;}");
}
      out.write("\n");
      out.write("            #content a {text-decoration: none;}\n");
      out.write("            #content tr:hover a {color:#972626;}\n");
      out.write("            #content a:hover {text-decoration: underline;}\n");
      out.write("            #content a.blocked {text-decoration: line-through;}\n");
      out.write("            a#addgroup{padding:4px;padding-left: 22px;background-image: url('small/application_view_icons.png'); background-position: center left; background-repeat: no-repeat; text-decoration: none; }\n");
      out.write("            a#addgroup:hover {color: #972626;text-decoration: underline;}\n");
      out.write("            #menu-navi {width: 95%; margin-left:10px; height: auto;}\n");
      out.write("            #menu-navi table {width:100%;}\n");
      out.write("            #menu-navi table td.oneNavi,#menu-navi table td.threeNavi  {width: 60px;}\n");
      out.write("            #menu-navi a {display: block; border: 1px solid #BFBFBF; width: 40px; height: 40px; margin: 10px; }\n");
      out.write("            #menu-navi a:hover {background-color: white;}\n");
      out.write("            a#backward {background-image: url('small/backward1.png'); background-position: center center; background-repeat: no-repeat;border-radius: 8px;}\n");
      out.write("            a#forward {background-image: url('small/forward1.png'); background-position: center center; background-repeat: no-repeat;border-radius: 8px; }\n");
      out.write("            a#backward:hover {background-image: url('small/backward.png'); }\n");
      out.write("            a#forward:hover {background-image: url('small/forward.png');}\n");
      out.write("            #content td.dop {width: 16px; padding: 4px}\n");
      out.write("            .fio{width: 160px;}\n");
      out.write("            #content td.first {width:16px; padding: 4px;}\n");
      out.write("        </style>\n");
      out.write("        <script type=\"text/javascript\" charset=\"utf-8\" src=\"alloy/build/yui/yui-min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"utf-8\" src=\"alloy/build/aui-base/aui-base-debug.js\"></script>\n");
      out.write("        <style>");
      out.print(CSS.getCSS(request));
      out.write("</style><style>");
      out.print(CSS3.getCSS("empDoc.jsp", request));
      out.write("</style>\n");
      out.write("    </head>\n");
      out.write("    <body id=\"empDoc_jsp\">\n");
      out.write("        <div id=\"content-wrapper\">\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <table id=\"tableH\">\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td id=\"tdlogo\">\n");
      out.write("                                <img src=\"logo.png\" id=\"logo\">\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <div id=\"head\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td id=\"slogan\" valign=\"center\">");
      out.print( slogan);
      out.write("</td>\n");
      out.write("                                                <td>\n");
      out.write("                                                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "poisk", out, true);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"foot\">\n");
      out.write("                                    <ul class=\"topMenu\">\n");
      out.write("                                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.xhtml", out, true);
      out.write("\n");
      out.write("                                        <li> <a href=\"http://exxo.ru/howto/documents-howto.html#find\" class=\"footmenu howto\" target=\"_blank\">?</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <table id=\"grid\" class=\"grid\">\n");
      out.write("                <tbody id=\"atbody\">\n");
      out.write("                    <tr id=\"tr\">\n");
      out.write("                        <td id=\"menu-td\" class=\"menu-td\" valign=\"top\">\n");
      out.write("                            <div class=\"exxo-menu exxo-shadow\" id=\"menu\">\n");
      out.write("                                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-doc.xhtml", out, true);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                            <div id=\"buttonsDons\"></div>\n");
      out.write("                            <div id=\"menuList\"><a href=\"docClassic.jsp");
      out.print(ll);
      out.write("\" id=\"addgroup\">qovluq strukturu</a></div>\n");
      out.write("                        </td>\n");
      out.write("                        <td id=\"column-3\" valign=\"top\">\n");
      out.write("                            <div id=\"content\" class=\"exxo-shadow\">");
      out.print(list);
      out.write("</div>\n");
      out.write("                            ");
      out.print(ND.navi);
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FOOTER", out, true);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            AUI().ready('aui-toolbar', function (A) {\n");
      out.write("                new A.Toolbar({activeState: true, children: [\n");
      out.write("                        {label: '', icon: 'check', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp';\n");
      out.write("                                }}},\n");
      out.write("                        {label: '', icon: 'dgeneral', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp?d=0';\n");
      out.write("                                }}},\n");
      out.write("                        {label: '', icon: 'dproject', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp?d=1';\n");
      out.write("                                }}}\n");
      out.write("                    ]}).render(A.one('#buttonsDons'));\n");
      out.write("                A.one('#buttonsDons').append(\"<br>\");\n");
      out.write("                new A.Toolbar({activeState: true, children: [\n");
      out.write("                        {label: '', icon: 'dgroup', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp?d=2';\n");
      out.write("                                }}},\n");
      out.write("                        {label: '', icon: 'dunit', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp?d=3';\n");
      out.write("                                }}},\n");
      out.write("                        {label: '', icon: 'dprivat', handler: {fn: function (e) {\n");
      out.write("                                    location = 'empDoc.jsp?d=4';\n");
      out.write("                                }}}\n");
      out.write("                    ]}).render(A.one('#buttonsDons'));\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/poisk.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/topMenu.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
