/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2018-08-16 12:05:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class processIns_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      BEANS.SLOGAN SLOGAN = null;
      synchronized (application) {
        SLOGAN = (BEANS.SLOGAN) _jspx_page_context.getAttribute("SLOGAN", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (SLOGAN == null){
          SLOGAN = new BEANS.SLOGAN();
          _jspx_page_context.setAttribute("SLOGAN", SLOGAN, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.CSSTotal CSS = null;
      synchronized (application) {
        CSS = (BEANS.CSSTotal) _jspx_page_context.getAttribute("CSS", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (CSS == null){
          CSS = new BEANS.CSSTotal();
          _jspx_page_context.setAttribute("CSS", CSS, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      BEANS.css1Bean CSS3 = null;
      CSS3 = (BEANS.css1Bean) _jspx_page_context.getAttribute("CSS3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CSS3 == null){
        CSS3 = new BEANS.css1Bean();
        _jspx_page_context.setAttribute("CSS3", CSS3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      BEANS.ProcessIns PROCESS = null;
      PROCESS = (BEANS.ProcessIns) _jspx_page_context.getAttribute("PROCESS", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (PROCESS == null){
        PROCESS = new BEANS.ProcessIns();
        _jspx_page_context.setAttribute("PROCESS", PROCESS, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }

    String slogan = SLOGAN.getSlogan(request);
    String role = (String) session.getAttribute("role");
    if (role.indexOf("a") < 0 && role.indexOf("h") < 0) {
        response.sendRedirect("notPermited.html");
    }
    String option = PROCESS.getOption(request);

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("        <title>yeni servis əlavə etmə forması</title>\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("        <meta http-equiv=\"content-style-type\" content=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"/FILES/alloy/build/aui-skin-classic/css/aui-skin-classic-all-min.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <script src=\"/FILES/alloy/build/aui/aui.js\" type=\"text/javascript\"></script>\n");
      out.write("        <link rel=\"stylesheet\" href=\"index.css\" type=\"text/css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"blue.css\" type=\"text/css\" />\n");
      out.write("        <style type=\"text/css\">\n");
      out.write("            @import url('css/topMenu.css');\n");
      out.write("            @import url('css/exxo.css');\n");
      out.write("            #content {width:575px; margin-left: 10px; border-color: #DEDEDE #DEDEDE #BFBFBF #DEDEDE;border-width: 1px;border-style: solid;  background-color: white; padding-top:20px;}\n");
      out.write("            table.table {width: 100%; }\n");
      out.write("            td.left {text-align:right;padding:10px;padding-right:20px;}\n");
      out.write("            td.right {text-align:left;}\n");
      out.write("            .table tr {border-bottom: 1px solid #dfdfdf;}\n");
      out.write("            #submit-button{width:100%;text-align:center;}\n");
      out.write("            #ok{margin:15px;padding: 5px; cursor: pointer;}\n");
      out.write("            table.table {font-size: 12px;}\n");
      out.write("            td.left {color: gray; width: 200px;}\n");
      out.write("            td.right input[type=text] {width: 300px; padding: 2px;}\n");
      out.write("            td.right {padding: 5px;}\n");
      out.write("            #content textarea {width: 300px; height: 100px;padding: 2px;} \n");
      out.write("            label {font-weight: normal;font-size:12px;}\n");
      out.write("            table.table tr:hover a {color:#972626;}\n");
      out.write("            .table a {color: #5B677D;text-decoration: none;}\n");
      out.write("            .table a:hover {text-decoration: underline;}    \n");
      out.write("            .strict {color:red;}\n");
      out.write("            #minToDeside,#minToOpen,#minToDo {width: 50px;}\n");
      out.write("        </style>\n");
      out.write("        <style>\n");
      out.write("            ");
      out.print(CSS.getCSS(request));
      out.write("\n");
      out.write("        </style>\n");
      out.write("        <style>\n");
      out.write("            ");
      out.print(CSS3.getCSS("processIns.jsp", request));
      out.write("\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body id=\"processIns_jsp\">\n");
      out.write("        <div id=\"content-wrapper\">\n");
      out.write("            <div id=\"header\">\n");
      out.write("                <table id=\"tableH\">\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td id=\"tdlogo\">\n");
      out.write("                                <img src=\"logo.png\" id=\"logo\"></td>\n");
      out.write("                            <td>\n");
      out.write("                                <div id=\"head\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td id=\"slogan\" valign=\"center\">");
      out.print( slogan);
      out.write("</td>\n");
      out.write("                                                <td>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "poisk", out, true);
      out.write("\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"foot\">\n");
      out.write("                                    <ul class=\"topMenu\">\n");
      out.write("                                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.xhtml", out, true);
      out.write("\n");
      out.write("                                        <li><a href=\"services.jsp\" class=\"footmenu\">Sonlandır</a></li>\n");
      out.write("                                        <li> <a href=\"http://exxo.ru/howto/service-howto.html#edit\" class=\"footmenu howto\" target=\"_blank\">?</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <table id=\"grid\" class=\"grid\">\n");
      out.write("                <tbody id=\"atbody\">\n");
      out.write("                    <tr id=\"tr\">\n");
      out.write("                        <td id=\"menu-td\" class=\"menu-td\" valign=\"top\">\n");
      out.write("                            <div class=\"exxo-menu exxo-shadow\" id=\"menu\">\n");
      out.write("                                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu-serv.xhtml", out, true);
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                        <td id=\"column-3\" valign=\"top\">\n");
      out.write("                            <div id=\"content\" class=\"exxo-shadow\">\n");
      out.write("                                <form method=\"post\" id=\"form\" name=\"form\" action=\"processIns\">\n");
      out.write("                                    <table>\n");
      out.write("                                        <tbody>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Ad</label></td>\n");
      out.write("                                                <td class=\"right\"><input name=\"name\" type=\"text\" id=\"name\" class=\"exxo-input\" ></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Açıqlama</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <textarea name=\"description\" rows=\"5\" cols=\"40\" class=\"exxo-textarea\"></textarea>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Sahibi</label></td>\n");
      out.write("                                                <td class=\"right\"><select name=\"owner\">");
      out.print( option);
      out.write("</select></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>İnspektor</label></td>\n");
      out.write("                                                <td class=\"right\"><select name=\"supervisor\">");
      out.print( option);
      out.write("</select></td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Şablon</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <textarea name=\"template\" rows=\"5\" cols=\"40\" class=\"exxo-textarea\"></textarea>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Açılma vaxtı</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <input name=\"minToOpen\" type=\"text\" id=\"minToOpen\" class=\"exxo-input\">\n");
      out.write("                                                    <select name=\"toOpen\">\n");
      out.write("                                                        <option value=\"1\" selected>dəqiqə</option>\n");
      out.write("                                                        <option value=\"60\">saat</option>\n");
      out.write("                                                        <option value=\"1440\">gün</option>\n");
      out.write("                                                        <option value=\"10080\">həftə</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Qərar vermək üçün vaxt</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <input name=\"minToDeside\" type=\"text\" id=\"minToDeside\" class=\"exxo-input\">\n");
      out.write("                                                    <select name=\"toDeside\">\n");
      out.write("                                                        <option value=\"1\" selected>dəqiqə</option>\n");
      out.write("                                                        <option value=\"60\">saat</option>\n");
      out.write("                                                        <option value=\"1440\">gün</option>\n");
      out.write("                                                        <option value=\"10080\">həftə</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>İcra vaxtı</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <input name=\"minToDo\" type=\"text\" id=\"minToDo\" class=\"exxo-input\">\n");
      out.write("                                                    <select name=\"toDo\">\n");
      out.write("                                                        <option value=\"1\" selected>dəqiqə</option>\n");
      out.write("                                                        <option value=\"60\">saat</option>\n");
      out.write("                                                        <option value=\"1440\">gün</option>\n");
      out.write("                                                        <option value=\"10080\">həftə</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                            <tr>\n");
      out.write("                                                <td class=\"left\"><label>Proses tipləri</label></td>\n");
      out.write("                                                <td class=\"right\">\n");
      out.write("                                                    <select name=\"type\">\n");
      out.write("                                                        <option value=\"simple\" SELECTED>Açıldı</option>\n");
      out.write("                                                        <option value=\"desideIsDone\">Həll edildi</option>\n");
      out.write("                                                        <option value=\"DoneIsDone\">İcra edildi</option>\n");
      out.write("                                                        <option value=\"answerIsDone\">Cavab verildi</option>\n");
      out.write("                                                    </select>\n");
      out.write("                                                </td>\n");
      out.write("                                            </tr>\n");
      out.write("                                        </tbody>\n");
      out.write("                                    </table>\n");
      out.write("                                    <div id=\"submit-button\">\n");
      out.write("                                        <input type=\"submit\" value=\"Yadda saxla\" id=\"ok\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>   \n");
      out.write("                        </td>\n");
      out.write("                    </tr> \n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "FOOTER", out, true);
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/poisk.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/topMenu.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
